### ISSUE TITLE
QNCache.copy

### ISSUE THREAD

**Issue by alorma** [Fewlaps/quitnow-cache#12]
It should be great if we can do something like:

```java
new QNCacheBuilder().createFromQNCache(anotherQNCacheInstance);
```

**Comment by rocboronat** [comment]
Why? Please, share a history when you want to double the data and have it unrelated.

By the way, the cache is something you should wrap with another class. Something near to your domain. And that class is a good place to put that data duplication.

**Comment by rocboronat** [comment]
Inactive issue: closed
