### ISSUE TITLE
So it stores only in RAM memory? no disk caching?

### ISSUE THREAD

**Issue by iRYO400** [Fewlaps/quitnow-cache#26]
Sup! Thanks for lib!

**Comment by rocboronat** [comment]
Hi! Yes, everything is only stored in memory. As we are only using it to avoid connecting to the network more than needed, we don't need to cache it on disk. But.. we're totally open to Pull Requests hihi

Thanks for the good words ❤️

**Comment by iRYO400** [comment]
@rocboronat is this ok, if all cached data erases after, for example, I travel from fragment1 to fragment2, then go back to fragment1? Inside one session

**Comment by rocboronat** [comment]
Well, if it's what the user expects, it's OK... :·) I mean, the library helps you in caching things for a limited time. You can use it as a tool to do what you need. If that's what you need... go on! :·)

**Comment by iRYO400** [comment]
it's not what I expect, I thought cache stores until user close an app

**Comment by rocboronat** [comment]
Then, I think that you are looking for the SharedPreferences Android class, not this cache :·) Let me suggest reading this link: https://developer.android.com/guide/topics/data/data-storage.html#pref

**Comment by rocboronat** [comment]
@iRYO400 i'm going to close this issue, as it's a question and I think that it has been answered. If you think that's not the case, feel free to reopen it :·)
