### ISSUE TITLE
Consider migrating from jcenter

### ISSUE THREAD

**Issue by TheFaithOne** [fewlaps/quitnow-cache#33]
Jfrog is going to deprecate and disable jcenter services - artifact migration will be needed

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by TheFaithOne** [comment]
Jcenter will stay as read only repository indefinitely, so I'll be closing this issue.
Quote from the article above:
UPDATE 4/27/2021: We listened to the community and will keep JCenter as a read-only repository indefinitely. Our customers and the community can continue to rely on JCenter as a reliable mirror for Java packages.

**Comment by rocboronat** [comment]
Thanks! 😁

I'll try to comment on this issue when I migrate my libraries to jcenter 😊
