### ISSUE TITLE
Automatic cast objects

### ISSUE THREAD

**Issue by alorma** [Fewlaps/quitnow-cache#7]
It should be great that we can do:

`Location cached = (Location ) cache.get("Location");`

without having to cast it, like:

`Location cached = cache.<Location>get("Location");`

Similar as `public static final <T> List<T> emptyList()` i java [Collections](http://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#emptyList())

**Comment by rocboronat** [comment]
That's a great feature! :+1:

**Comment by rocboronat** [comment]
@alorma did this with 41420adc30b7e4de1fb4598b6cd72224e533cf89
